angus-c/just

README.md, packages/function-partial/README.md, packages/function-partial/index.js, test/function-partial/index.js
The documentation is unclear that `partial()` expects to be passed `global.___` as the marker for a missing variable. Using `undefined` is explicit an clearer in intention and doesn't require additional global definitions.
=> remove global.___ in favor of undefined keyword

packages/array-last/index.js, test/array-last/index.js
On several ocassions I'm interested in the last value of an array, but the input might be undefined. This PR ensures that `last` doesn't throw if the input `arr` is either null or undefined, so that it's not necessary to do something like `last(arr || [])`.
Feel free to close this if handling this edge input case is invalid.
=> Don't throw on array-last when input is undefined or null

packages/array-range/index.js, test/array-range/index.js
Previously an infinite loop would occur if `start` was not a multiple of `stop`.
=> Support decimals as well

README.md, packages/function-curry/README.md, packages/function-curry/index.js, test/function-curry/index.js
so:
```js
function addThree(x, y, z) {
return x + y + z
}
curry(addThree)(1)(4)(4) //=> 9
curry(addThree)(1, 4)(4) //=> 9
curry(addThree)(1, 4, 4) //=> 9
curry(addThree)(1)(4, 4) //=> 9
```
might be considered a breaking change because `curry(convertor)` no longer returns you `convertor`, but a curried version of `convertor`.
=> Make curry translate a polyadic function to a sequence of nested unary functions

packages/object-entries/README.md, packages/object-entries/index.js, packages/object-entries/package.json, test/index.js, test/object-entries/index.js
Here object-entries acts a little bit like the proposed Object.entries but
stays in line with the object-values implementation. That is mostly to
say that it will work on entries(new String('abc')) but not entries('abc').
It will, generally, take an object and return it's key/value pairs.
entries({b: 4, a: 8}) // [['b', 4], ['a', 8]]
=> Adding object-entries in kind with object-values

README.md, packages/array-split-at/README.md, packages/array-split-at/index.js, packages/array-split-at/package.json, packages/array-tail/README.md, test/array-split-at/index.js, test/function-debounce/index.js
A new array package to split an array into two at a given position. Examples:
```javascript
import splitAt from 'just-split-at';
splitAt([1, 2, 3, 4, 5], 2); // [[1, 2], [3, 4, 5]]
splitAt([{a: 1}, {b: 1}, {c: 1}], -1); // [[{a: 1}, {b: 1}], [{c: 1}]]
splitAt([], 2); // [[], []]
splitAt(null, 1); // undefined
splitAt(undefined, 1); // undefined
```
PR also includes some minor cleanup of READMEs – happy to move to another PR if desired.
=> Add just-split-at package

packages/collection-diff/index.js, test/collection-diff/index.js
This worked when the second object contained the null and the first
object contains a value. This extends that so that it works on both
sides.
Having null / undefined on the left and anything on the right is
considered a replace, including replacing null with undefined and vice
versa.
=> Support null and undefined in first object

packages/collection-compare/index.js, packages/collection-compare/package.json, test/collection-compare/index.js
This fixes a bug where compare would throw `TypeError: Cannot convert undefined or null to object` when a property goes from object to null.
=> Issue: https://github.com/angus-c/just/issues/98

packages/object-pick/index.js
1. Some quotes on strings were missing.
2. Picking non-existent keys is [no longer supported](https://github.com/angus-c/just/commit/2b4afcdd206a030ff7b74ae40541a6e6a2193d58#diff-3d976488e63ac579c491f3cf92a53176R14).
=> Clean up object-pick comments

README.md
I noticed that the link for `just-merge` didn't go anywhere on the top Read me, so I decided to update it.
=> Add merge to top level README

README.md, TRADEOFFS.md, packages/object-safe-get/README.md, packages/object-safe-get/index.js, test/object-safe-get/index.js
While updating our codebase from lodash, I found some more discrepancies due to missing support for 3rd param when 1st param is falsy. Updated it here and it's now lodash-compatible for those 4 cases:
```javascript
_.get(null, 'a'); // undefined
_.get(undefined, ['a']); // undefined
_.get(null, 'a', 42); // 42
_.get(undefined, ['a'], 42); // 42
```
However this change is probably breaking / semver-major:
```diff
-_.get(null, 'a'); // null
+_.get(null, 'a'); // undefined
```
Do you think it's okay to keep this, with the goal of better lodash compat?
=> object-safe-get: even more lodash compat + docs

packages/string-camel-case/index.js
The `strict` option was removed from `camelCase` in #112. There are no other options, so the parameter is no longer needed.
=> Remove unused parameter

packages/object-typeof/index.js
result should already be in lowercase, no need to lowercase it again
=> remove redundant toLowerCase() in just-typeof

packages/number-clamp/index.js, test/number-clamp/index.js
When I first saw the example, it got me confused. I later realized it was a typo. Here is a fix.
=> docs(number-clamp): fix example in comments

README.md, packages/object-has/LICENSE, packages/object-has/README.md, packages/object-has/index.js, packages/object-has/package.json, test/object-has/index.js
Hi,
we often want to check just the existence on a deep object and avoid access prototypes or large data. For this purpose it would be cool to consider a .hasOwnProperty util.
Kind regards
=> feat: add object-safe-hasownproperty

packages/number-is-prime/README.md, packages/number-is-prime/index.js, test/number-is-prime/index.js
When a given number is a square of prime, the function returns `true` while the number is composite.
[the sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)
- Fix the bug. 
- Add a test for square of prime.
- Add `Try it now` link to README.
=> Fix number-is-prime logic

packages/array-split/index.js, test/array-split/index.js
- Correct the result of the example `split([1, 2, 3, 4, 5, 6], null)`. It returns an array of the same elements as the first argument and does not throw an error.
- Add tests for the above example.
- Change the second error message to more accurate expression.
=> improve the examples and the tests for array-split

packages/array-split/index.d.ts, packages/array-split/index.tests.ts
This adds types for array split.  
For `split(null)` I couldn't get this to work without `strictNullChecks`.  `NonNullable<T[]>` also didn't work.  
Still, these types improve upon the existing return types by inferring the from the type passed in.
=> add ts types for array split

package.json, packages/array-split/index.d.ts, packages/array-split/index.tests.ts
- Add `npm run test:type` command.
- Add the command in `test` script.
- Fix type test of array-spilit, for the function actually accepts `null` as its second argument.
=> Add an npm script to run tests for types

packages/array-flatten/index.js, test/array-flatten/index.js
When removing the override in array-flatten test, other tests are broken (`collection-clone` and `collection-diff-apply`)
=> Temporarily removing `Array.prototype.flatten` override

packages/array-group-by/index.d.ts, packages/array-group-by/index.tests.ts
Add a type definition and tests for [array-group-by](https://github.com/angus-c/just/blob/master/packages/array-group-by/index.js).
=> Add type definition for array-group-by

packages/object-merge/index.d.ts, packages/object-merge/index.tests.ts, packages/object-merge/package.json
I copied these typings from the DefinitelyTyped repository.
<hr>
I [opened a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52729) to remove this project's typings from the DefinitelyTyped repository and noticed that the "just-merge" typings didn't make it over here yet. If this PR lands, I can finish removing all of the "just" typings from that repo.
=> Add typings for object-merge

packages/object-filter/index.d.ts, packages/object-filter/index.tests.ts, packages/object-filter/package.json
A bit of type gymnastics here to cause an error when passing in a Set or Map, but otherwise not too complex.
=> Add type definitions for object-filter package

packages/function-throttle/index.d.ts
Currently `just/throttle` returns `Function & Methods`, which is not safe nor assignable to `addEventListener`.
TypeScript doc says...
> This is an untyped function call and is generally best avoided because of the unsafe any return type.
> If you need to accept an arbitrary function but don’t intend to call it, the type () => void is generally safer.
Use generic function type instead, which will improve type safety and make it easier to use.
Since generic `Func` is inferred from the parameter, we are not forced to write like `throttle<() => void>`. So this PR would not be a breaking change.
=> Make throttle type generic

packages/string-truncate/index.js, test/string-truncate/index.js
Small typographic refinement that anything functional.
Replaces the 3 periods _..._ approximation in the `truncate` method with the single typographic _…_ character. 
Saves a small amount of real-estate when used + marginally less characters in the codebase
=> replace 3 period approximation with correct ellipsis character

packages/object-map-values/index.d.ts, packages/object-map-values/index.tests.ts
The generic types allow Typescript to infer the correct return type.
=> Add generic types to `just-map-values`

packages/string-replace-all/index.d.ts, packages/string-replace-all/index.tests.ts, packages/string-replace-all/package.json
Added types for `just-replace-all`. The generic type allows typescript to infer the correct return type for a given string.
See the below screenshot for an example in action:
=> Add generic typescript types for 'just-replace-all'

packages/string-capitalize/index.d.ts
Currently when using `capitalize` in a Typescript project, the return type is just a string, but Typescript has [a Capitalize generic type](https://www.typescriptlang.org/docs/handbook/utility-types.html#capitalizestringtype) which can take in a string constant type and return the capitalized string constant type. This allows the return value of say `capitalize('hi')` to be exactly `'Hi'` rather than just `string`.
Here's a screenshot of how it looks when using the changed utility in a project:
=> Add generic type goodness to 'just-capitalize'

packages/array-percentile/index.d.ts, packages/array-percentile/index.js, packages/array-percentile/index.tests.ts, packages/array-percentile/package.json, test/array-percentile/index.js
I was testing the percentile algorithm, and noticed it was giving different values than other tools like google sheets and python. 
After a ton of research I realized there are two main algorithms. Percentile exclusive, and percentile inclusive. The default alg for google sheets, excel, R, and python are all the inclusive version.
I changed it to the R7 algorithm specified in [the nist spec](https://www.itl.nist.gov/div898/handbook/prc/section2/prc262.htm). This seems to be the most useful/commonly used version. It might be worth adding more under different exports in the future.
I also changed the percentage parameter to be decimal percentage instead. Chose to do this because percentage values are easier to work with between 0 and 1. If you want me to change this back I can, I just …
=> changed percentile algorithm

packages/collection-diff-apply/index.esm.js, packages/collection-diff/index.esm.js
When this library was converted to ESM, the packages with named exports weren't named exports anymore, rather an object `{ 
diff, jsonThing }` was exported as `default`, which broke ESM builds.
This PR fixes that issue
=> Fix diff and diff-apply ESM error

packages/string-squash/index.d.ts, packages/string-squash/index.tests.ts, packages/string-squash/package.json
Adds generic type to `just-squash` which can convert the type of the string appropriately
See screenshot:
=> Types: Generic type for just-squash

packages/object-flip/index.d.ts, packages/object-flip/index.tests.ts, packages/object-flip/package.json
Add generic type for just-flip-object.
Typescript will infer the correct shape of the flipped object whenever possible. See example:
=> Types: Add generic type for just-flip-object

packages/array-union/index.d.ts
Adds better support for readonly arrays to the types for `just-union`.
See example:
=> Types: better generic type for just-union

packages/array-random/index.d.ts, packages/array-random/index.tests.ts
There was an error with the return type of the just-random function
When the ts compiler didn't know if the array was empty or not it would set the return type as undefined
example:
```
const array: number[] = [1, 2, 3];
// This caused a TS error
const result1: number = random(array);
// This didn't cause a TS error
const result2: undefined = random(array);
```
I've modified the types so that in this case TS will return the type or undefined
example:
```
const array: number[] = [1, 2, 3];
// This doesn't cause a TS error
const result: number | undefined = random(array);
```
I fixed this error and added new test cases to cover
=> Fixed array-random types

packages/array-last/index.d.ts, packages/array-last/index.tests.ts
Add generic type overload to just-last.
Typescript can now determine the exact type of the last array for readonly arrays:
=> Add more specific generic type overload to just-last

packages/array-tail/index.d.ts, packages/array-tail/index.tests.ts
Adds handling for readonly arrays in `tail`.
Now you can do something like the following
```typescript
const arr = [1,2,3,4] as const;
const t: [2,3,4] = tail(arr);
```
=> Add readonly array handling for array-tail

packages/array-intersect/index.d.ts, packages/array-intersect/index.tests.ts
This adds the ability to use readonly arrays with `intersect`, previously they threw a type error.
=> Add readonly array capability to array-intersect

packages/object-map-values/index.d.ts, packages/object-map-values/index.tests.ts
Simplified and improved the types for object-map-values
The previous types would throw a TS Error on test3
=> Improved types and types tests for object-map-values

packages/object-deep-map-values/LICENSE, packages/object-deep-map-values/README.md, packages/object-deep-map-values/index.d.ts, packages/object-deep-map-values/index.js, packages/object-deep-map-values/index.mjs, packages/object-deep-map-values/index.tests.ts, packages/object-deep-map-values/package.json, packages/object-deep-map-values/rollup.config.js, test/object-deep-map-values/index.js
Added function to deeply map an objects values
example:
```js
import deepMapValues from "just-deep-map-values";
const squareFn = (number) => number * number;
deepMapValues({ a: 1, b: { c: 2, d: { e: 3 } } }, squareFn); // => { a: 1, b: { c: 4, d: { e: 9 } } }
```
=> Added object-deep-map-values

package.json
Previously the test script and therefore the build step would pass even if there were lint errors. This change causes the script to exit when there are lint errors and therefore fail the build
=> Fixed test script to exit on lint errors

README.md, packages/function-partial/README.md, templates/global.template
The global.template was misaligned with the README.md
When we want to make edits we should remember to edit the templates instead of the outputted files.
I'll find some time soon to add a feature to template-mate which inputs a warning line at the top. something like:
```md
```
=> aligned global.template with README.md

README.md, md-variables.json, packages/function-partial/README.md
the just-debounce-it section in the README was malformatted. therefore the anchor-link in the TOC did not work either.
thanks!
=> Remove excess triple-backticks before just-debounce-it

README.md, md-variables.json, packages/array-last/README.md
Removed extra backticks in array-last examples which was causing improper formatting in README
=> Fix README error

packages/collection-compare/index.js, packages/collection-compare/index.mjs, test/collection-compare/index.js
This fixes angus-c/just#423 where primitives compared with their equivalent primitive wrapper object would return true or false, depending on the order of the arguments.
=> Issue: https://github.com/angus-c/just/issues/423

packages/string-template/index.js, packages/string-template/index.mjs, test/string-template/index.js
This fixes an issue where `just-template` would throw the following error if a nested variable was found without a corresponding value.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'bbb')
```
=> Fix error for just-template when unresolved nested variables

packages/function-flip/index.d.ts, packages/function-flip/index.tests.ts
In the previous version, the type of `flip((x: string, y: number) => any)` was incorrectly inferred as `(x: string, y: number) => any`. It should be `(x: number, y: string) => any` so I fixed it.
=> Fix types of function-flip

README.md, md-variables.json, packages/array-sort-by/README.md
This updates the `just-array-sort-by` README to show the correct importing syntax.
=> update just-array-sort-by readme to reflect correct import

packages/collection-diff/index.js, test/collection-diff/index.js
We were reversing remove diff at the end of each cycle instead of once at the end. So if the property to be removed was nested an even number of times, the remove diffs ended up in the wrong order
Fixes #443
=> Fix final remove order in diff util

packages/collection-compare/index.d.ts, packages/collection-compare/index.tests.ts, packages/collection-compare/package.json
Fixes #460. 
The solution to this ended up being slightly more complex than I thought, because the final two test cases check that it is a type error to compare a `Number` to a `number`
There's some weird non-transitive `extends` behavior here , which is why the original `Exclude<T, Primitive>` was used.
- `Number extends object` = true
- `number extends Number` = true
- `number extends object` = false
So I changed the type parameters to `compare<T1 extends object, T2 extends T1 & object>`, which keeps the tests passing while also allowing it to work with generic arguments.
I also added the `types` entry to the export map for compatibility with TS 4.7 node16/nodenext module resolution.
=> Update compare types to work when the input is a generic

packages/object-merge/index.d.ts, packages/object-merge/index.tests.ts
This improves the flexibility of the `merge` utility!
Updated tests and `test-types` passes.
Before, the return and props of the merge utility would always be just an object type.
:x: Not good.
Now using generics, typescript can figure out the return and props types.
:heavy_check_mark: Good!
=> Add generic for object-merge type

.eslintrc, package.json, yarn.lock
ESLint now uses the `@typescript-eslint` parser to parse `.ts` files. `.js` files still use the default parser. This was done by using the `overrides` key in the eslint config to set the parser specifically for `.ts` files.
**NOTE:** I did not lint any files as part of this PR. My recommendation would be that if the eslint setup in this PR is approved, then a second commit should be made where all the `ts` files in the codebase are linted, and possibly also have `prettier` run on them.
Closes #472
=> configured eslint to work on ts files

packages/function-demethodize/index.d.ts, packages/function-demethodize/index.tests.ts, packages/function-demethodize/package.json
I think this is the last package that needed typings. 
Currently there are 2 signatures you can call this with:
```ts
demethodize<string, [string], string>("".split);
//OR
demethodize<string, "split">("".split);
```
The best way to use this in my opinion is to specify the function typing on the variable you assign the function too, as such:
```ts
const split: (p:string, a:string) => string[] = demethodize("".split)
```
Unfortunately, you have to manually pass generics to this function in order to use it (unless you use the method shown directly above). This is because when you call `demethodize("".split)` typescript has no way of knowing what type you called the `.split` method on.
I wasn't able to get the generics working exactly how I wanted to, ideally, you would only have to specify …
=> Add typings for function-demethodize

packages/collection-compare/index.d.ts, packages/collection-compare/index.tests.ts
Fixes https://github.com/angus-c/just/issues/476
- Typings now just take 2 values of unknown type & returns a boolean, which matches the JS
=> Simplifies typings on `just-compare`

README.md
On the first example, there is a code highlight missing: just made sure it works specifying `js` as code used there.
=> Add code highlight to first example

packages/function-partial/index.d.ts, packages/function-partial/index.tests.ts
The `index.ts` and `index.d.ts` exports are different.
https://github.com/angus-c/just/blob/4636c2c6b6df2500df5217f579818283916d2215/packages/function-partial/index.js#L1
=> fix funtion-partial export type

packages/number-is-prime/index.js, packages/number-is-prime/index.mjs
Now it skips all even numbers during for-loop.
=> Halved execution time for Prime number check.

packages/object-reduce/index.d.ts, packages/object-reduce/index.tests.ts
Changed to use default export in typings.
=> Fix typings for object-reduce(use default export)

README.md, templates/globalPackage.template
After the recent changes renaming `.js` files to `.cjs` all the source links in the README.md were broken. This change fixes them and links to the source folder instead of directly to a file
=> Fixed global template

packages/array-permutations/index.cjs, packages/array-permutations/index.mjs, test/array-permutations/index.cjs
=> replace concat with spread: items can be arrays

packages/collection-diff/index.cjs, packages/collection-diff/index.mjs, test/collection-diff/index.cjs
see https://github.com/angus-c/just/issues/544
=> fix: op type error with an new empty string property

packages/collection-diff/index.cjs, packages/collection-diff/index.mjs, test/collection-diff/index.cjs, test/object-extend/index.cjs
Remove recursing multiple permutations in favor of deciding upfront whether left or right trim is the most efficient.
=> Fix #543. Simplify left vs right trim logic

packages/array-index/README.md
Updated the readme file for `just-index` to reflect that the code snippet throws an error instead of returning undefined, which was originally stated. This change ensures that the code snippet description is accurate and helpful for developers.
**Code snippet:**
```js
index([], null);	// throws error
index({}, 'id');	// throws error
```
**URL:**
- https://anguscroll.com/just/just-index
=> Fix incorrect code snippet description for `just-index`

packages/object-is-empty/index.d.ts, packages/object-is-empty/index.tests.ts
I think the idea was for `ReturnFalseValues` to represent values that could return false, but the effect is that the type checker sees these as "always returns false". Really, `string` and `any[]` should be in the same category as `object` and should be treated as "needs further inspection"
=> Fix is-empty return type
